name: restaurant_management_mobile
description: Mobile application for Restaurant Management project
version: 1.0.0
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  flutter_images_slider: ^0.0.2
  flutter_vector_icons: ^0.1.0
  gradient_widgets: ^0.4.1
  intl: ^0.15.8
  shared_preferences: ^0.5.2
  equatable: ^0.1.6
  bloc: ^0.13.0
  rxdart: ^0.22.0
  flutter_bloc: ^0.13.0
  image_picker: ^0.4.0
  firebase_storage: ^3.0.0
  pull_to_refresh: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.1"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Rukola
      fonts:
        - asset: assets/fonts/iciel-rukola.otf
  assets:
    - assets/icons/
    - assets/images/
