name: restaurant_management_mobile
description: Mobile application for Restaurant Management project
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  rxdart: ^0.22.0
  http: ^0.12.0+2
  flutter_images_slider: ^0.0.2
  flutter_vector_icons: ^0.1.0
  gradient_widgets: ^0.4.1
  intl: ^0.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Rukola
      fonts:
        - asset: assets/fonts/iciel-rukola.otf
  assets:
    - assets/icons/
    - assets/images/
